import type { PersonaKey } from "@/features/persona/personas";

export type Evidence = {
  id: string;
  persona: PersonaKey[];
  value: string;
  unit?: string;
  repo: string;
  path: string;
  how: string;
  observedAt: string;
  public: boolean;
};

export const EVIDENCE: readonly Evidence[] = [
  {
    id: "dronenexus.tests.collected",
    persona: ["projects"],
    value: "3,800",
    unit: "tests collected",
    repo: "NyXkim5/DroneNexus",
    path: "services/",
    how: "python3 -m pytest --collect-only -q services/",
    observedAt: "2026-09-05",
    public: false,
  },
  {
    id: "dronenexus.tests.files",
    persona: ["projects"],
    value: "221",
    unit: "test files",
    repo: "NyXkim5/DroneNexus",
    path: "services/",
    how: "find services -name 'test_*.py' | wc -l",
    observedAt: "2026-09-05",
    public: false,
  },
  {
    id: "dronenexus.core.lines",
    persona: ["projects"],
    value: "77,616",
    unit: "lines in services/core",
    repo: "NyXkim5/DroneNexus",
    path: "services/core/",
    how: "find services/core -name '*.py' -not -path '*__pycache__*' | xargs wc -l",
    observedAt: "2026-09-05",
    public: false,
  },
  {
    id: "dronenexus.yolo.latency",
    persona: ["projects", "work"],
    value: "57.63 → 40.65 ms",
    unit: "YOLO mean latency, M1 Max CPU, 100 runs",
    repo: "NyXkim5/DroneNexus",
    path: "docs/perception/latency-benchmark.md",
    how: "read the mean column for baseline and fine-tuned ONNX export",
    observedAt: "2026-09-05",
    public: false,
  },
  {
    id: "dronenexus.siting.bound",
    persona: ["projects"],
    value: "1 − 1/e",
    unit: "approximation guarantee, greedy siting",
    repo: "NyXkim5/DroneNexus",
    path: "services/core/siting/greedy.py",
    how: "read the greedy_select docstring",
    observedAt: "2026-09-05",
    public: false,
  },
  {
    id: "sonicfly.bearing.rmse",
    persona: ["projects"],
    value: "2.292 → 0.605 m",
    unit: "range RMSE after covariance fix",
    repo: "sonicfly-research",
    path: "BEARING_REGRESSION.md",
    how: "read the benchmark table, 60 runs x 600 steps",
    observedAt: "2026-09-05",
    public: false,
  },
  {
    id: "archvbrain.eval.verifiedQuotes",
    persona: ["projects", "work"],
    value: "13 of 18",
    unit: "quotes byte-exact in stored text",
    repo: "ArchvBrain",
    path: "eval_data/verified_extraction_baseline.json",
    how: "totals.quotesStoredTextExact / totals.quotes in the committed baseline",
    observedAt: "2026-09-05",
    public: false,
  },
  {
    id: "archvbrain.eval.falseAnchors",
    persona: ["projects", "work"],
    value: "0",
    unit: "false anchors across 13 offset-carrying quotes",
    repo: "ArchvBrain",
    path: "eval_data/verified_extraction_baseline.json",
    how: "totals.falseAnchors in the committed baseline, rates.falseAnchorRate = 0.0",
    observedAt: "2026-09-05",
    public: false,
  },
  {
    id: "archvbrain.eval.goldRows",
    persona: ["projects", "work"],
    value: "45",
    unit: "hand-labelled gold rows across three datasets",
    repo: "ArchvBrain",
    path: "golden_reasoning_dataset.json, hallucination_dataset.json, conflict_resolution_dataset.json",
    how: "counted rows in each file: 15 + 20 + 10",
    observedAt: "2026-09-05",
    public: false,
  },
  {
    id: "iris.tenant.suiteLines",
    persona: ["projects", "work"],
    value: "3,928",
    unit: "lines of adversarial tenant-isolation tests",
    repo: "Iris",
    path: "backend/tests/test_tenant_isolation.py",
    how: "wc -l backend/tests/test_tenant_isolation.py",
    observedAt: "2026-09-05",
    public: false,
  },
  {
    id: "iris.gold.fixtures",
    persona: ["projects", "work"],
    value: "22",
    unit: "gold fixtures, 12,200 lines",
    repo: "Iris",
    path: "backend/tests/fixtures/*/gold.json",
    how: "ls backend/tests/fixtures/*/gold.json | wc -l; wc -l on the same",
    observedAt: "2026-09-05",
    public: false,
  },
  {
    id: "metis.sources.enabled",
    persona: ["projects", "work"],
    value: "130 of 135",
    unit: "curated sources enabled",
    repo: "singularity",
    path: "registry.ts",
    how: "grep -c 'enabled: true' registry.ts against total entries",
    observedAt: "2026-09-05",
    public: false,
  },
  {
    id: "bamboo.tests.files",
    persona: ["projects", "design", "work"],
    value: "313",
    unit: "test files",
    repo: "NyXkim5/nutrition-app",
    path: "src/",
    how: "find src -name '*.test.ts*' | wc -l",
    observedAt: "2026-09-05",
    public: false,
  },
  {
    id: "bamboo.gate.passing",
    persona: ["projects", "design"],
    value: "1,979 + 697",
    unit: "vitest + jest passing at last gate",
    repo: "NyXkim5/nutrition-app",
    path: "HANDOFF.md",
    how: "read the gate table dated 2026-08-07",
    observedAt: "2026-09-05",
    public: false,
  },
  {
    id: "bamboo.asc.appId",
    persona: ["projects", "design"],
    value: "6784845593",
    unit: "App Store Connect app id",
    repo: "NyXkim5/nutrition-app",
    path: "eas.json",
    how: "submit.production.ios.ascAppId",
    observedAt: "2026-09-05",
    public: false,
  },
  {
    id: "roleindex.rows.live",
    persona: ["work"],
    value: "533",
    unit: "curated roles, refreshed daily",
    repo: "NyXkim5/summer-2027-role-index",
    path: "stats.json",
    how: "stats.json total, refreshed 2026-09-04 by the GitHub Action",
    observedAt: "2026-09-05",
    public: true,
  },
  {
    id: "dronenexus.yolo.map50",
    persona: ["projects"],
    value: "0.949",
    unit: "mAP50 at epoch 5, drone_seraphim_v1",
    repo: "NyXkim5/DroneNexus",
    path: "backend/runs/detect/models/runs/drone_seraphim_v1/results.csv",
    how: "metrics/mAP50(B) on the last row of results.csv",
    observedAt: "2026-09-06",
    public: false,
  },
  {
    id: "dronenexus.yolo.precision",
    persona: ["projects"],
    value: "0.943",
    unit: "precision at epoch 5, recall 0.898",
    repo: "NyXkim5/DroneNexus",
    path: "backend/runs/detect/models/runs/drone_seraphim_v1/results.csv",
    how: "metrics/precision(B) and metrics/recall(B) on the last row of results.csv",
    observedAt: "2026-09-06",
    public: false,
  },
  {
    id: "overwatch.tests.passed",
    persona: ["projects"],
    value: "125",
    unit: "HUD unit tests passing",
    repo: "NyXkim5/DroneNexus",
    path: "overwatch-tests-final.png",
    how: "capture of the HUD test run, 125 passed, kept in the home directory",
    observedAt: "2026-09-06",
    public: false,
  },
  {
    id: "dronenexus.latency.onnx.p95",
    persona: ["projects"],
    value: "43.79",
    unit: "ms p95 for the ONNX detector, baseline p95 63.51",
    repo: "NyXkim5/DroneNexus",
    path: "docs/perception/latency-benchmark.md",
    how: "Measured results table, rows Fine-tune v2 (ONNX) and Baseline (Seraphim), column p95, 100 timed runs on an M1 Max CPU",
    observedAt: "2026-09-06",
    public: false,
  },
  {
    id: "dronenexus.msp.arm_frame.bytes",
    persona: ["projects"],
    value: "22",
    unit: "bytes in one MSP v1 arm frame",
    repo: "NyXkim5/DroneNexus",
    path: "services/core/msp/protocol.py",
    how: "len(MSPEncoder.encode(MSP_SET_RAW_RC, 16-byte payload)) run by scripts/figures/msp-frame.py",
    observedAt: "2026-09-06",
    public: false,
  },
  {
    id: "iris.isolation.route_cases",
    persona: ["projects", "work"],
    value: "77",
    unit: "route cases, 8 refused in Python rather than SQL",
    repo: "NyXkim5/Iris",
    path: "backend/tests/test_tenant_isolation.py",
    how: "count of @case( decorators, sql_scoped=False counted for the Python-decided subset",
    observedAt: "2026-09-06",
    public: false,
  },
  {
    id: "iris.isolation.test_functions",
    persona: ["projects", "work"],
    value: "25",
    unit: "test definitions across seven proof layers",
    repo: "NyXkim5/Iris",
    path: "backend/tests/test_tenant_isolation.py",
    how: "def test_ definitions grouped by the file's own section headers; parametrized tests execute more than once",
    observedAt: "2026-09-06",
    public: false,
  },
  {
    id: "metis.sources.state_controlled",
    persona: ["projects", "work"],
    value: "7",
    unit: "state-controlled sources, all tier T6, never standalone",
    repo: "singularity",
    path: "services/ingest/src/sources/registry.ts",
    how: "entries with state_controlled: true in CURATED_REGISTRY",
    observedAt: "2026-09-06",
    public: false,
  },
  {
    id: "pan.real.range_rmse",
    persona: ["projects"],
    value: "1.473 → 1.354 m",
    unit: "range RMSE on 2,296 real flight frames, shipped chain vs recommended",
    repo: "NyXkim5/pan",
    path: "bench/results/gen3_real.json",
    how: "results.shipped and results.honest_r from python3 -m bench.real --tag gen3_real, Duke's held-out test set, better on 7 of 10 trajectories",
    observedAt: "2026-09-06",
    public: false,
  },
  {
    id: "pan.real.bearing_mae",
    persona: ["projects"],
    value: "30.99 → 30.54 deg",
    unit: "bearing MAE on the same real frames, better on only 4 of 10 trajectories",
    repo: "NyXkim5/pan",
    path: "bench/results/gen3_real.json",
    how: "results.shipped and results.honest_r bearing_mae_deg, the paper reports 31.2 for the shipped chain",
    observedAt: "2026-09-06",
    public: false,
  },
  {
    id: "pan.tests",
    persona: ["projects"],
    value: "17",
    unit: "pytest cases in the derivative repo",
    repo: "NyXkim5/pan",
    path: "tests/",
    how: "python3 -m pytest tests -q, 17 passed",
    observedAt: "2026-09-06",
    public: false,
  },
  {
    id: "hermes.bench.decode",
    persona: ["projects", "work"],
    value: "103.3 ± 2.6",
    unit: "decode tokens per second, lfm2-350m, M1 Max, prefill 758.7",
    repo: "NyXkim5/hermes",
    path: "flutter/bench/results/bench_pp128_tg64.json",
    how: "flutter/bench/bench.dart, pp136 tg64, temperature 0, one warmup, five repetitions, mean and sample standard deviation",
    observedAt: "2026-09-06",
    public: false,
  },
  {
    id: "hermes.first_token",
    persona: ["projects", "work"],
    value: "38.6 ms",
    unit: "first token visible in Dart, engine TTFT 32.3 ms, never visible before Generation 3",
    repo: "NyXkim5/hermes",
    path: "flutter/bench/results/gen3_after_liveness.log",
    how: "completeAsync on a worker isolate, calling isolate ran 60 ten-millisecond ticks during a 594 ms generation, 0 before",
    observedAt: "2026-09-06",
    public: false,
  },
  {
    id: "hermes.tests",
    persona: ["projects", "work"],
    value: "46",
    unit: "Dart tests passing, 32 pure and 14 against the real dylib",
    repo: "NyXkim5/hermes",
    path: "flutter/test/",
    how: "flutter test after Generation 3, no Dart suite existed upstream",
    observedAt: "2026-09-06",
    public: false,
  },
  {
    id: "optum.rfp.volume",
    persona: ["work"],
    value: "Tens of thousands",
    unit: "RFPs a year through one platform",
    repo: "Optum",
    path: "n/a",
    how: "Jay's statement, 2026-07-11. Qualitative by rule, no figure exists.",
    observedAt: "2026-09-05",
    public: false,
  },
  {
    id: "github.contributions.total",
    persona: ["work"],
    value: "2,084",
    unit: "GitHub contributions in the last year, refreshed daily",
    repo: "NyXkim5/JAYnKIM",
    path: "src/features/work/data/contributions.json",
    how: "contributionCalendar.totalContributions, refreshed daily by .github/workflows/contributions.yml",
    observedAt: "2026-09-06",
    public: true,
  },
  {
    id: "github.contributions.commits",
    persona: ["work"],
    value: "208",
    unit: "commits in public repos in the last year, refreshed daily",
    repo: "NyXkim5/JAYnKIM",
    path: "src/features/work/data/contributions.json",
    how: "contributionsCollection.totalCommitContributions, public repositories only, refreshed daily by .github/workflows/contributions.yml",
    observedAt: "2026-09-06",
    public: true,
  },
  {
    id: "github.contributions.restricted",
    persona: ["work"],
    value: "1,859",
    unit: "contributions in private repos in the last year, refreshed daily",
    repo: "NyXkim5/JAYnKIM",
    path: "src/features/work/data/contributions.json",
    how: "contributionsCollection.restrictedContributionsCount, GitHub gives no type breakdown for private activity, refreshed daily by .github/workflows/contributions.yml",
    observedAt: "2026-09-06",
    public: true,
  },
  {
    id: "dronenexus.siting.coverage",
    persona: ["projects"],
    value: "71.8%",
    unit: "expected coverage, 4 of 36 candidate masts at 900 m on the ridge scenario",
    repo: "NyXkim5/JAYnKIM",
    path: "src/features/specimen/data/hardware.json",
    how: "source.note expected_fraction=0.7176 from scripts/specimen/hardware.py, the same run scripts/figures/siting-coverage.py draws",
    observedAt: "2026-09-06",
    public: true,
  },
  {
    id: "stealth.va.demos",
    persona: ["work"],
    value: "3",
    unit: "demos with the VA, discovery RFP in progress",
    repo: "Stealth Startup",
    path: "n/a",
    how: "Jay's statement, 2026-09-06. No public artifact exists.",
    observedAt: "2026-09-06",
    public: false,
  },
];

export function findEvidence(id: string): Evidence | undefined {
  return EVIDENCE.find((e) => e.id === id);
}

export function evidenceFor(persona: PersonaKey): Evidence[] {
  return EVIDENCE.filter((e) => e.persona.includes(persona));
}

export function sourceHref(e: Evidence): string {
  if (e.public) return `https://github.com/${e.repo}/blob/main/${e.path}`;
  return `/${e.persona[0]}#${e.id}`;
}
