import type { PersonaKey } from "@/features/persona/personas";

export type Evidence = {
  id: string;
  persona: PersonaKey[];
  value: string;
  unit?: string;
  repo: string;
  path: string;
  how: string;
  observedAt: string;
  public: boolean;
};

export const EVIDENCE: readonly Evidence[] = [
  {
    id: "dronenexus.tests.collected",
    persona: ["projects"],
    value: "3,800",
    unit: "tests collected",
    repo: "NyXkim5/DroneNexus",
    path: "services/",
    how: "python3 -m pytest --collect-only -q services/",
    observedAt: "2026-09-05",
    public: false,
  },
  {
    id: "dronenexus.tests.files",
    persona: ["projects"],
    value: "221",
    unit: "test files",
    repo: "NyXkim5/DroneNexus",
    path: "services/",
    how: "find services -name 'test_*.py' | wc -l",
    observedAt: "2026-09-05",
    public: false,
  },
  {
    id: "dronenexus.core.lines",
    persona: ["projects"],
    value: "77,616",
    unit: "lines in services/core",
    repo: "NyXkim5/DroneNexus",
    path: "services/core/",
    how: "find services/core -name '*.py' -not -path '*__pycache__*' | xargs wc -l",
    observedAt: "2026-09-05",
    public: false,
  },
  {
    id: "dronenexus.yolo.latency",
    persona: ["projects", "work"],
    value: "57.63 → 40.65 ms",
    unit: "YOLO mean latency, M1 Max CPU, 100 runs",
    repo: "NyXkim5/DroneNexus",
    path: "docs/perception/latency-benchmark.md",
    how: "read the mean column for baseline and fine-tuned ONNX export",
    observedAt: "2026-09-05",
    public: false,
  },
  {
    id: "dronenexus.siting.bound",
    persona: ["projects"],
    value: "1 − 1/e",
    unit: "approximation guarantee, greedy siting",
    repo: "NyXkim5/DroneNexus",
    path: "services/core/siting/greedy.py",
    how: "read the greedy_select docstring",
    observedAt: "2026-09-05",
    public: false,
  },
  {
    id: "sonicfly.bearing.rmse",
    persona: ["projects"],
    value: "2.292 → 0.605 m",
    unit: "range RMSE after covariance fix",
    repo: "sonicfly-research",
    path: "BEARING_REGRESSION.md",
    how: "read the benchmark table, 60 runs x 600 steps",
    observedAt: "2026-09-05",
    public: false,
  },
  {
    id: "archvbrain.eval.verifiedQuotes",
    persona: ["projects", "work"],
    value: "13 of 18",
    unit: "quotes byte-exact in stored text",
    repo: "ArchvBrain",
    path: "eval_data/verified_extraction_baseline.json",
    how: "totals.quotesStoredTextExact / totals.quotes in the committed baseline",
    observedAt: "2026-09-05",
    public: false,
  },
  {
    id: "archvbrain.eval.falseAnchors",
    persona: ["projects", "work"],
    value: "0",
    unit: "false anchors across 13 offset-carrying quotes",
    repo: "ArchvBrain",
    path: "eval_data/verified_extraction_baseline.json",
    how: "totals.falseAnchors in the committed baseline, rates.falseAnchorRate = 0.0",
    observedAt: "2026-09-05",
    public: false,
  },
  {
    id: "archvbrain.eval.goldRows",
    persona: ["projects", "work"],
    value: "45",
    unit: "hand-labelled gold rows across three datasets",
    repo: "ArchvBrain",
    path: "golden_reasoning_dataset.json, hallucination_dataset.json, conflict_resolution_dataset.json",
    how: "counted rows in each file: 15 + 20 + 10",
    observedAt: "2026-09-05",
    public: false,
  },
  {
    id: "iris.tenant.suiteLines",
    persona: ["projects", "work"],
    value: "3,928",
    unit: "lines of adversarial tenant-isolation tests",
    repo: "Iris",
    path: "backend/tests/test_tenant_isolation.py",
    how: "wc -l backend/tests/test_tenant_isolation.py",
    observedAt: "2026-09-05",
    public: false,
  },
  {
    id: "iris.gold.fixtures",
    persona: ["projects", "work"],
    value: "22",
    unit: "gold fixtures, 12,200 lines",
    repo: "Iris",
    path: "backend/tests/fixtures/*/gold.json",
    how: "ls backend/tests/fixtures/*/gold.json | wc -l; wc -l on the same",
    observedAt: "2026-09-05",
    public: false,
  },
  {
    id: "metis.sources.enabled",
    persona: ["projects", "work"],
    value: "130 of 135",
    unit: "curated sources enabled",
    repo: "singularity",
    path: "registry.ts",
    how: "grep -c 'enabled: true' registry.ts against total entries",
    observedAt: "2026-09-05",
    public: false,
  },
  {
    id: "bamboo.tests.files",
    persona: ["projects", "design", "work"],
    value: "313",
    unit: "test files",
    repo: "NyXkim5/nutrition-app",
    path: "src/",
    how: "find src -name '*.test.ts*' | wc -l",
    observedAt: "2026-09-05",
    public: false,
  },
  {
    id: "bamboo.gate.passing",
    persona: ["projects", "design"],
    value: "1,979 + 697",
    unit: "vitest + jest passing at last gate",
    repo: "NyXkim5/nutrition-app",
    path: "HANDOFF.md",
    how: "read the gate table dated 2026-08-07",
    observedAt: "2026-09-05",
    public: false,
  },
  {
    id: "bamboo.asc.appId",
    persona: ["projects", "design"],
    value: "6784845593",
    unit: "App Store Connect app id",
    repo: "NyXkim5/nutrition-app",
    path: "eas.json",
    how: "submit.production.ios.ascAppId",
    observedAt: "2026-09-05",
    public: false,
  },
  {
    id: "roleindex.rows.live",
    persona: ["work"],
    value: "533",
    unit: "curated roles, refreshed daily",
    repo: "NyXkim5/summer-2027-role-index",
    path: "stats.json",
    how: "stats.json total, refreshed 2026-09-04 by the GitHub Action",
    observedAt: "2026-09-05",
    public: true,
  },
  {
    id: "dronenexus.yolo.map50",
    persona: ["projects"],
    value: "0.949",
    unit: "mAP50 at epoch 5, drone_seraphim_v1",
    repo: "NyXkim5/DroneNexus",
    path: "backend/runs/detect/models/runs/drone_seraphim_v1/results.csv",
    how: "metrics/mAP50(B) on the last row of results.csv",
    observedAt: "2026-09-06",
    public: false,
  },
  {
    id: "dronenexus.yolo.precision",
    persona: ["projects"],
    value: "0.943",
    unit: "precision at epoch 5, recall 0.898",
    repo: "NyXkim5/DroneNexus",
    path: "backend/runs/detect/models/runs/drone_seraphim_v1/results.csv",
    how: "metrics/precision(B) and metrics/recall(B) on the last row of results.csv",
    observedAt: "2026-09-06",
    public: false,
  },
  {
    id: "overwatch.tests.passed",
    persona: ["projects"],
    value: "125",
    unit: "HUD unit tests passing",
    repo: "NyXkim5/DroneNexus",
    path: "overwatch-tests-final.png",
    how: "capture of the HUD test run, 125 passed, kept in the home directory",
    observedAt: "2026-09-06",
    public: false,
  },
  {
    id: "dronenexus.latency.onnx.p95",
    persona: ["projects"],
    value: "43.79",
    unit: "ms p95 for the ONNX detector, baseline p95 63.51",
    repo: "NyXkim5/DroneNexus",
    path: "docs/perception/latency-benchmark.md",
    how: "Measured results table, rows Fine-tune v2 (ONNX) and Baseline (Seraphim), column p95, 100 timed runs on an M1 Max CPU",
    observedAt: "2026-09-06",
    public: false,
  },
  {
    id: "dronenexus.msp.arm_frame.bytes",
    persona: ["projects"],
    value: "22",
    unit: "bytes in one MSP v1 arm frame",
    repo: "NyXkim5/DroneNexus",
    path: "services/core/msp/protocol.py",
    how: "len(MSPEncoder.encode(MSP_SET_RAW_RC, 16-byte payload)) run by scripts/figures/msp-frame.py",
    observedAt: "2026-09-06",
    public: false,
  },
  {
    id: "iris.isolation.route_cases",
    persona: ["projects", "work"],
    value: "77",
    unit: "route cases, 8 refused in Python rather than SQL",
    repo: "NyXkim5/Iris",
    path: "backend/tests/test_tenant_isolation.py",
    how: "count of @case( decorators, sql_scoped=False counted for the Python-decided subset",
    observedAt: "2026-09-06",
    public: false,
  },
  {
    id: "iris.isolation.test_functions",
    persona: ["projects", "work"],
    value: "25",
    unit: "test definitions across seven proof layers",
    repo: "NyXkim5/Iris",
    path: "backend/tests/test_tenant_isolation.py",
    how: "def test_ definitions grouped by the file's own section headers; parametrized tests execute more than once",
    observedAt: "2026-09-06",
    public: false,
  },
  {
    id: "metis.sources.state_controlled",
    persona: ["projects", "work"],
    value: "7",
    unit: "state-controlled sources, all tier T6, never standalone",
    repo: "singularity",
    path: "services/ingest/src/sources/registry.ts",
    how: "entries with state_controlled: true in CURATED_REGISTRY",
    observedAt: "2026-09-06",
    public: false,
  },
  {
    id: "pan.real.range_rmse",
    persona: ["projects"],
    value: "1.473 → 1.354 m",
    unit: "range RMSE on 2,296 real flight frames, shipped chain vs recommended",
    repo: "NyXkim5/pan",
    path: "bench/results/gen3_real.json",
    how: "results.shipped and results.honest_r from python3 -m bench.real --tag gen3_real, Duke's held-out test set, better on 7 of 10 trajectories",
    observedAt: "2026-09-06",
    public: false,
  },
  {
    id: "pan.real.bearing_mae",
    persona: ["projects"],
    value: "30.99 → 30.54 deg",
    unit: "bearing MAE on the same real frames, better on only 4 of 10 trajectories",
    repo: "NyXkim5/pan",
    path: "bench/results/gen3_real.json",
    how: "results.shipped and results.honest_r bearing_mae_deg, the paper reports 31.2 for the shipped chain",
    observedAt: "2026-09-06",
    public: false,
  },
  {
    id: "pan.tests",
    persona: ["projects"],
    value: "17",
    unit: "pytest cases in the derivative repo",
    repo: "NyXkim5/pan",
    path: "tests/",
    how: "python3 -m pytest tests -q, 17 passed",
    observedAt: "2026-09-06",
    public: false,
  },
  {
    id: "hermes.bench.decode",
    persona: ["projects", "work"],
    value: "103.3 ± 2.6",
    unit: "decode tokens per second, lfm2-350m, M1 Max, prefill 758.7",
    repo: "NyXkim5/hermes",
    path: "flutter/bench/results/bench_pp128_tg64.json",
    how: "flutter/bench/bench.dart, pp136 tg64, temperature 0, one warmup, five repetitions, mean and sample standard deviation",
    observedAt: "2026-09-06",
    public: false,
  },
  {
    id: "hermes.first_token",
    persona: ["projects", "work"],
    value: "38.6 ms",
    unit: "first token visible in Dart, engine TTFT 32.3 ms, never visible before Generation 3",
    repo: "NyXkim5/hermes",
    path: "flutter/bench/results/gen3_after_liveness.log",
    how: "completeAsync on a worker isolate, calling isolate ran 60 ten-millisecond ticks during a 594 ms generation, 0 before",
    observedAt: "2026-09-06",
    public: false,
  },
  {
    id: "hermes.tests",
    persona: ["projects", "work"],
    value: "46",
    unit: "Dart tests passing, 32 pure and 14 against the real dylib",
    repo: "NyXkim5/hermes",
    path: "flutter/test/",
    how: "flutter test after Generation 3, no Dart suite existed upstream",
    observedAt: "2026-09-06",
    public: false,
  },
  {
    id: "optum.rfp.volume",
    persona: ["work"],
    value: "Tens of thousands",
    unit: "RFPs a year through one platform",
    repo: "Optum",
    path: "n/a",
    how: "Jay's statement, 2026-07-11. Qualitative by rule, no figure exists.",
    observedAt: "2026-09-05",
    public: false,
  },
  {
    id: "github.contributions.total",
    persona: ["work"],
    value: "2,084",
    unit: "GitHub contributions in the last year, refreshed daily",
    repo: "NyXkim5/JAYnKIM",
    path: "src/features/work/data/contributions.json",
    how: "contributionCalendar.totalContributions, refreshed daily by .github/workflows/contributions.yml",
    observedAt: "2026-09-06",
    public: true,
  },
  {
    id: "github.contributions.commits",
    persona: ["work"],
    value: "208",
    unit: "commits in public repos in the last year, refreshed daily",
    repo: "NyXkim5/JAYnKIM",
    path: "src/features/work/data/contributions.json",
    how: "contributionsCollection.totalCommitContributions, public repositories only, refreshed daily by .github/workflows/contributions.yml",
    observedAt: "2026-09-06",
    public: true,
  },
  {
    id: "github.contributions.restricted",
    persona: ["work"],
    value: "1,859",
    unit: "contributions in private repos in the last year, refreshed daily",
    repo: "NyXkim5/JAYnKIM",
    path: "src/features/work/data/contributions.json",
    how: "contributionsCollection.restrictedContributionsCount, GitHub gives no type breakdown for private activity, refreshed daily by .github/workflows/contributions.yml",
    observedAt: "2026-09-06",
    public: true,
  },
  {
    id: "dronenexus.siting.coverage",
    persona: ["projects"],
    value: "71.8%",
    unit: "expected coverage, 4 of 36 candidate masts at 900 m on the ridge scenario",
    repo: "NyXkim5/JAYnKIM",
    path: "src/features/specimen/data/hardware.json",
    how: "source.note expected_fraction=0.7176 from scripts/specimen/hardware.py, the same run scripts/figures/siting-coverage.py draws",
    observedAt: "2026-09-06",
    public: true,
  },
  {
    id: "pantheon.fusion.mota",
    persona: ["projects"],
    value: "0.956 vs 0.872",
    unit: "MOTA, in-house tracker against Stone Soup, same 216 detections",
    repo: "NyXkim5/DroneNexus",
    path: "docs/superpowers/handoffs/theia-2026-09-08.md",
    how: "benchmark_fusion.py --backend both --scenario cartesian --seed 1 --targets 3 --duration 30, scored by py-motmetrics at a 25 m match radius, table pasted verbatim into the handoff",
    observedAt: "2026-09-09",
    public: false,
  },
  {
    id: "pantheon.fusion.update_ms",
    persona: ["projects"],
    value: "0.43 vs 6.13 ms",
    unit: "wall clock per tracker update, about 14x apart",
    repo: "NyXkim5/DroneNexus",
    path: "docs/superpowers/handoffs/theia-2026-09-08.md",
    how: "update(ms) column of the same Cartesian benchmark run, 60 ticks",
    observedAt: "2026-09-09",
    public: false,
  },
  {
    id: "pantheon.discovery.repos",
    persona: ["projects"],
    value: "133",
    unit: "repos catalogued, stars and last push and license read from the GitHub API",
    repo: "NyXkim5/DroneNexus",
    path: "docs/DISCOVERY_CATALOG_2026-09.md",
    how: "counted the repo rows across every Project table in the catalog, 133 unique slugs, checked against the 98 repos already cited in the July sweep",
    observedAt: "2026-09-09",
    public: false,
  },
  {
    id: "pantheon.mirrors",
    persona: ["projects"],
    value: "10",
    unit: "upstream repos mirrored as nine named private forks",
    repo: "NyXkim5/DroneNexus",
    path: "docs/superpowers/specs/2026-09-08-pantheon-wave0-1-design.md",
    how: "the Repos table, nine fork names over ten upstreams because the acoustic fork mirrors two",
    observedAt: "2026-09-09",
    public: false,
  },
  {
    id: "pantheon.gate.tests",
    persona: ["projects"],
    value: "3,922 + 453",
    unit: "Python and JavaScript tests passing at the last gate",
    repo: "NyXkim5/DroneNexus",
    path: "docs/superpowers/handoffs/wave0-baseline-2026-09-08.md",
    how: "the Wave 2 post-review gate row: make test exit 0 with 3922 passed, pnpm test 453 passed, ruff and mypy exit 0",
    observedAt: "2026-09-09",
    public: false,
  },
  {
    id: "pantheon.cot.angelia",
    persona: ["projects"],
    value: "5",
    unit: "decimal places of position agreement, checked by an outside CoT parser",
    repo: "NyXkim5/DroneNexus",
    path: "src/hud/js/__tests__/cot.angelia.test.js",
    how: "node-CoT 14.52.1 parses the Python formatter's fixture and asserts type, uid and lat/lon, then converts it to GeoJSON and protobuf",
    observedAt: "2026-09-09",
    public: false,
  },
  {
    id: "pantheon.live.tracks",
    persona: ["projects"],
    value: "2",
    unit: "fused tracks drawn on the HUD from the acoustic replay",
    repo: "NyXkim5/DroneNexus",
    path: "docs/DEMO_ECHO.md",
    how: "ran the Echo sensor plan against services/core/main.py, then connected the HUD to the same websocket. scripts/smoke_track_state.py exited 0 on the first TRACK_STATE packet and two unknown-air symbols drew at the two node positions",
    observedAt: "2026-09-09",
    public: false,
  },
  {
    id: "stealth.va.demos",
    persona: ["work"],
    value: "3",
    unit: "demos with the VA, discovery RFP in progress",
    repo: "Stealth Startup",
    path: "n/a",
    how: "Jay's statement, 2026-09-06. No public artifact exists.",
    observedAt: "2026-09-06",
    public: false,
  },
  {
    id: "shipstability.tests.passing",
    persona: ["projects"],
    value: "276",
    unit: "tests passing",
    repo: "local/ship-stability",
    path: "ship_stability/",
    how: "python3 -m pytest ship_stability/ -q, real exit code 0 read from $?",
    observedAt: "2026-09-11",
    public: false,
  },
  {
    id: "shipstability.wallsided.agreement",
    persona: ["projects"],
    value: "1e-9",
    unit: "metres, agreement with the wall-sided closed form",
    repo: "local/ship-stability",
    path: "ship_stability/test_stability.py",
    how: "test_gz_matches_wall_sided_theory_inside_its_valid_range, asserted at every degree inside the wall-sided range",
    observedAt: "2026-09-11",
    public: false,
  },
  {
    id: "shipstability.imo.criteria",
    persona: ["projects"],
    value: "6",
    unit: "IMO 2008 IS Code part A 2.2 criteria checked",
    repo: "local/ship-stability",
    path: "ship_stability/criteria.py",
    how: "Each threshold read from the code text and cross-checked against UK MCA MSIS43 and EU Directive 2009/45/EC. Constants carry their paragraph number in a comment.",
    observedAt: "2026-09-11",
    public: false,
  },
  {
    id: "ehslog.tests.passing",
    persona: ["projects"],
    value: "400",
    unit: "tests passing",
    repo: "local/ehs-incident-log",
    path: "ehs_incident_log/",
    how: "python3 -m pytest ehs_incident_log/ -q",
    observedAt: "2026-09-11",
    public: false,
  },
  {
    id: "ehslog.cfr.sections",
    persona: ["projects"],
    value: "19",
    unit: "distinct 29 CFR 1904 sections cited in code",
    repo: "local/ehs-incident-log",
    path: "ehs_incident_log/",
    how: "grep -rhoE '1904\\.[0-9]+' ehs_incident_log/*.py | sort -u | wc -l",
    observedAt: "2026-09-11",
    public: false,
  },
  {
    id: "ehslog.firstaid.items",
    persona: ["projects"],
    value: "14",
    unit: "first aid treatments encoded from 29 CFR 1904.7(b)(5)(ii)",
    repo: "local/ehs-incident-log",
    path: "ehs_incident_log/recordability.py",
    how: "len(FirstAidTreatment), the full A to N list, each member carrying its citation",
    observedAt: "2026-09-11",
    public: false,
  },
  {
    id: "shipstability.kn.identity",
    persona: ["projects"],
    value: "3.3e-16",
    unit: "metres, worst error in GZ = KN - KG sin(heel)",
    repo: "local/ship-stability",
    path: "ship_stability/test_crosscurves.py",
    how: "One cross-curve table reproduced three separately integrated GZ curves at KG 1.5, 2.5 and 3.4, checked at every angle from 0 to 60 degrees",
    observedAt: "2026-09-11",
    public: false,
  },
  {
    id: "shipstability.freetrim.effect",
    persona: ["projects"],
    value: "6.7",
    unit: "percent fall in GZ at 40 degrees once the hull is free to trim",
    repo: "local/ship-stability",
    path: "ship_stability/test_freetrim.py",
    how: "Sheer barge 24 by 8, 3.0 m deep forward and 6.0 m aft, draft 2.5 m, KG 2.0. The fore and aft symmetric box barge is the control and moves by less than 1e-9 m",
    observedAt: "2026-09-11",
    public: false,
  },
  {
    id: "ehslog.bls.rows",
    persona: ["projects"],
    value: "975",
    unit: "BLS private industry incidence rate rows, reference year 2024",
    repo: "local/ehs-incident-log",
    path: "ehs_incident_log/benchmarks.py",
    how: "Parsed from BLS Table 1, Incidence rates of nonfatal occupational injuries and illnesses by industry and case types, 2024. Standard errors are UNVERIFIED and printed as such",
    observedAt: "2026-09-11",
    public: false,
  },
  {
    id: "ehslog.concurrency.workers",
    persona: ["projects"],
    value: "6",
    unit: "concurrent OS processes writing one log without losing a case",
    repo: "local/ehs-incident-log",
    path: "ehs_incident_log/test_concurrency.py",
    how: "Six subprocesses busy-wait on a shared start time, then write 12 cases each. Asserts every case present, the hash chain verifies, and sequence numbers run 1..n with no gaps",
    observedAt: "2026-09-11",
    public: false,
  },
  {
    id: "ontologyseed.tests.passing",
    persona: ["projects"],
    value: "266",
    unit: "tests passing, 188 Python and 78 TypeScript",
    repo: "local/palantir-ontology-seed",
    path: "generator/, ontology/, functions/src/",
    how: "python3 -m pytest generator ontology -q gave 188 passed, then pnpm test in functions/ gave 78 passed. Both exit codes read from $?, both 0. tsc --noEmit also exited 0",
    observedAt: "2026-09-11",
    public: false,
  },
  {
    id: "ontologyseed.ontology.objects",
    persona: ["projects"],
    value: "8",
    unit: "object types, with 7 link types, 8 action types and 1 interface",
    repo: "local/palantir-ontology-seed",
    path: "ontology/ontology.json",
    how: "Counted the top level lists in ontology.json. A validator of 44 tests holds the definition to its own datasets, and asserts that opening an engagement needs the authorizer role and that no action deletes anything",
    observedAt: "2026-09-11",
    public: false,
  },
  {
    id: "ontologyseed.dataset.detections",
    persona: ["projects"],
    value: "3,816",
    unit: "synthetic detections, reproducible byte for byte from one seed",
    repo: "local/palantir-ontology-seed",
    path: "data/raw_detections.csv",
    how: "Row count of the committed CSV. Regenerating it with python3 generator/cli.py into a scratch directory and running diff -r against data/ exited 0 with no differences",
    observedAt: "2026-09-11",
    public: false,
  },
  {
    id: "maritime.tests.passing",
    persona: ["projects"],
    value: "120",
    unit: "tests passing across the six maritime test files",
    repo: "NyXkim5/DroneNexus",
    path: "services/sensor/tests/",
    how: "python3 -m pytest on the six test_maritime_*.py files from the repo root on branch maritime-scenario, real exit code 0 read from $?",
    observedAt: "2026-09-11",
    public: false,
  },
  {
    id: "maritime.scenarios.named",
    persona: ["projects"],
    value: "6",
    unit: "named scenarios on one replay driver",
    repo: "NyXkim5/DroneNexus",
    path: "services/sensor/scenarios/library.py",
    how: "closing-swarm, multi-axis, sequential-waves, crossing-civilian, sensor-degradation and sea-skimmer, read from the builders in library.py",
    observedAt: "2026-09-11",
    public: false,
  },
  {
    id: "artemis.mutation.gaps",
    persona: ["projects"],
    value: "25",
    unit: "of 108 mutants survived the original suite, 12 of them real gaps",
    repo: "NyXkim5/artemis",
    path: "firmware/tools/mutate.py",
    how: "python3 tools/mutate.py, run three times: against the original 37-test suite restored from commit 73d035d, against the current 49-test suite, and against the sanitizer build. 83, 95 and 96 killed. Every mutant is proved to have entered the binary by comparing the object hash against the baseline, and 0 of 108 came back unchanged",
    observedAt: "2026-09-11",
    public: false,
  },
  {
    id: "artemis.firmware.tests",
    persona: ["projects"],
    value: "49",
    unit: "tests passing, 359 checks",
    repo: "NyXkim5/artemis",
    path: "firmware/",
    how: "make clean && make test in firmware/, real exit code 0 read from $?. make sanitize gives the same 49 and 359 under ASan and UBSan",
    observedAt: "2026-09-11",
    public: false,
  },
  {
    id: "artemis.tracking.tests",
    persona: ["projects"],
    value: "266",
    unit: "tests passing",
    repo: "NyXkim5/artemis",
    path: "tracking/artemis_track/",
    how: "python3 -m pytest artemis_track from tracking/, with __pycache__ cleared first, real exit code 0 read from $?",
    observedAt: "2026-09-11",
    public: false,
  },
  {
    id: "artemis.loop.tick",
    persona: ["projects"],
    value: "4.42",
    unit: "ms median tick, against a 20 ms budget at 50 Hz",
    repo: "NyXkim5/artemis",
    path: "tracking/artemis_track/latency.py",
    how: "2000 ticks of the step scenario through the loop's own latency instrument. p99 5.37 ms and one measured tick at 27.4 ms. The camera read is 3.18 ms of the median. Desktop Python, not a Raspberry Pi, so these are a floor and not the budget",
    observedAt: "2026-09-11",
    public: false,
  },
  {
    id: "maritime.reposuite.passing",
    persona: ["projects"],
    value: "4,156",
    unit: "tests passing across the whole repository",
    repo: "NyXkim5/DroneNexus",
    path: "packages/shared/python/aeacus/verticals.py",
    how: "python3 -m pytest -q from the repo root on branch maritime-scenario, 4156 passed and 4 skipped in 581s, real exit code 0 read from $?. Before the one line fix the same command gave 1 failed and 4155 passed, the failure being test_every_top_level_module_is_owned_or_allowlisted",
    observedAt: "2026-09-12",
    public: false,
  },
];

export function findEvidence(id: string): Evidence | undefined {
  return EVIDENCE.find((e) => e.id === id);
}

export function evidenceFor(persona: PersonaKey): Evidence[] {
  return EVIDENCE.filter((e) => e.persona.includes(persona));
}

export function sourceHref(e: Evidence): string {
  if (e.public) return `https://github.com/${e.repo}/blob/main/${e.path}`;
  return `/${e.persona[0]}#${e.id}`;
}
